language: cpp
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - RUN_TEST=1 THREADING="none" BUILD_CONFIG="auto"
  - RUN_TEST=1 THREADING="none" BUILD_CONFIG="reference"
  - RUN_TEST=0 THREADING="openmp" BUILD_CONFIG="auto"
  - RUN_TEST=0 THREADING="pthreads" BUILD_CONFIG="auto"

matrix:
  allow_failures:
  exclude:
  
before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew install gcc@6 llvm@3.9;
        brew link --force llvm@3.9;
    fi'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.9
    packages:
    - gcc-6
    - g++-6
    - clang-3.9
    
install:
  - if [ "$CC" = "gcc" ] ; then export CC="gcc-6" CXX="g++-6"; fi
  - if [ "$CC" = "clang" ] ; then export CC="clang-3.9" CXX="clang++-3.9"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$CXX" = "clang++-3.9" ]; then export CXX="clang-3.9"; fi

script:
  - $CC --version
  - $CXX --version
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cat /proc/cpuinfo; fi
  - ./configure CC=$CC CXX=$CXX --enable-threading=$THREADING --enable-config=$BUILD_CONFIG || cat config.log src/external/tci/config.log
  - make -j 2
  - if [ $RUN_TEST -eq 1 ]; then travis_wait 30 bin/test; fi
